@startuml
    folder "src" as src_b874d07 {
      object "MshEnv" as msh_env_b1c29247 {
      }
      folder "convert-strategy" as convert_strategy_42693489 {
        class "ConvertStrategyBase64ToString" as convert_strategy_base64_to_string_1a7fae76 {
          convert(str?: string): string | undefined
        }
        interface "ConvertStrategy" as convert_strategy_5952dd71 {
          + convert(str?: string): T | undefined
        }
        class "ConvertStrategyToBoolean" as convert_strategy_to_boolean_b5f6361d {
          convert(str?: string): boolean | undefined
        }
        class "ConvertStrategyToJson" as convert_strategy_to_json_3a59481 {
          convert(str?: string): T | undefined
        }
        class "ConvertStrategyToNumber" as convert_strategy_to_number_5542359a {
          convert(str?: string): number | undefined
        }
        class "ConvertStrategyToString" as convert_strategy_to_string_8b9651ec {
          convert(str?: string): string | undefined
        }
      }
      folder "env" as env_339e04b5 {
        class "EnvFactory" as env_factory_3969ec87 {
          # _env: Env
          base64: EnvType<string>
          boolean: EnvType<boolean>
          constructor(params: {\n     names: string[];\n     locationStrategies: LocationStrategy[];\n     namingStrategies: NamingStrategy[] \n})
          json: EnvType<T>
          number: EnvType<number>
          string: EnvType<string>
        }
        class "Env" as env_1c6f07cd {
          # _envNames: string[]
          # _locationStrategies: LocationStrategy[]
          # _namingStrategies: NamingStrategy[]
          constructor(params: {\n     names: string[];\n     locationStrategies: LocationStrategy[];\n     namingStrategies: NamingStrategy[] \n})
          envValue: string | undefined
          names: string[]
        }
        class "EnvType" as env_type_b658b1cb {
          # _allowedValues: T[]
          # _allowedValuesDoNotContain(value?: T): boolean
          # _allowedValuesToString: string
          # _convertStrategy: ConvertStrategy<T>
          # _createError(msg: string): Error
          # _defaultValue: T | undefined
          # _env: Env
          # _envName: string
          # _loggerDebug(msg: string,\n     ...args: {\n     [k: string]: any \n}[]): void
          # _validateAllowedValues(value?: T): void
          allowed(...args: T[]): EnvType<T>
          constructor(params: {\n     convertStrategy: ConvertStrategy<T>;\n     env: Env \n})
          default(defaultValue: T): EnvType<T>
          optional: T | undefined
          required: T
        }
      }
      folder "location-strategy" as location_strategy_afd28503 {
        class "LocationStrategyCliArgsMinimist" as location_strategy_cli_args_minimist_d9ad8ea4 {
          # _args: T
          # _miniOpts: minimist.Opts
          constructor(params?: {\n     options?: Options;\n     args?: string[] \n})
          valueByName(name: string): string | undefined
        }
        class "LocationStrategyDockerSecrets" as location_strategy_docker_secrets_aadf16f9 {
          valueByName(name: string): string | undefined
        }
        class "LocationStrategyEnvironment" as location_strategy_environment_114d0f30 {
          valueByName(name: string): string | undefined
        }
        interface "LocationStrategy" as location_strategy_347a72bb {
          + valueByName(name: string): string | undefined
        }
      }
      folder "naming-strategy" as naming_strategy_797f00dc {
        interface "NamingStrategy" as naming_strategy_1f64e9e4 {
          + names(name: string[]): string[]
        }
        class "NamingStrategyPrefixName" as naming_strategy_prefix_name_7ee8fa60 {
          # _prefix: string
          constructor(prefix: string)
          names(names: string[]): string[]
        }
        class "NamingStrategySimpleName" as naming_strategy_simple_name_c1354e3e {
          names(names: string | string[]): string[]
        }
        class "NamingStrategySuffixName" as naming_strategy_suffix_name_eca33007 {
          # _suffix: string
          constructor(suffix: string)
          names(names: string[]): string[]
        }
      }
    }
  env_factory_3969ec87 -up-> convert_strategy_base64_to_string_1a7fae76
  env_factory_3969ec87 -up-> convert_strategy_to_boolean_b5f6361d
  env_factory_3969ec87 -up-> convert_strategy_to_json_3a59481
  env_factory_3969ec87 -up-> convert_strategy_to_number_5542359a
  env_factory_3969ec87 -up-> convert_strategy_to_string_8b9651ec
  env_factory_3969ec87 -up-> env_type_b658b1cb
  env_type_b658b1cb -up-> env_type_b658b1cb
  msh_env_b1c29247 -up-> env_factory_3969ec87
@enduml